set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR "$ENV{CARGO_CFG_TARGET_ARCH}")
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(SCARLET_COMPAT_INCLUDE
    "${CMAKE_CURRENT_LIST_DIR}/../moonlight-sys/platform/scarlet/include")
add_compile_options(
    "-I${SCARLET_COMPAT_INCLUDE}"
    "-fno-stack-protector")

if("$ENV{CARGO_CFG_TARGET_ARCH}" STREQUAL "riscv64")
    add_compile_options("-march=rv64gc" "-mabi=lp64d")
endif()

set(OPUS_FIXED_POINT ON CACHE BOOL "" FORCE)
set(OPUS_ENABLE_FLOAT_API OFF CACHE BOOL "" FORCE)
set(OPUS_DISABLE_INTRINSICS ON CACHE BOOL "" FORCE)
set(OPUS_HARDENING OFF CACHE BOOL "" FORCE)
set(OPUS_STACK_PROTECTOR OFF CACHE BOOL "" FORCE)
set(OPUS_FORTIFY_SOURCE OFF CACHE BOOL "" FORCE)
